#!/usr/bin/env bash

# Popular zxy's:
# 7/26/50
# 9/105/201
# 10/210/403
# 14/3370/6451

if [ "$1" == "" ]; then echo "This program requires arguments"; exit; fi

zxy=$1
z=`echo $zxy | sed 's:/.*::'`
base=santafe$z
tiles=tiles$z

echo $zxy $z $base $tiles

echo 'building osm'
bin/zxy2osm $zxy > $base.osm
echo 'building json'
node_modules/osmtogeojson/osmtogeojson < $base.osm > $base.json

echo 'building osm json roads'
bin/json2roads < $base.json | bin/minifyjson > ${base}roads.json
# echo 'getting .png base map'
# curl https://tile.openstreetmap.org/${zxy}.png > $base.png

echo 'running tippecanoe'
# tippecanoe/tippecanoe -z14 -f --no-simplification-of-shared-nodes -o ${base}.mbtiles ${base}roads.json
bin/tippecanoe -zg -f -l roads -n "SantaFe Roads" -o ${base}roads.mbtiles ${base}roads.json

# echo 'building vt json'
# vt2geojson $tiles/$zxy.pbf > ${base}vt0.json

# echo 'building vt roads json'
# bin/json2roads < ${base}vt0.json | bin/minifyjson > ${base}vt.json

# exit

